Feature/setup
Tarek1311/C4Medical_Maids pull request #10
Opened 2022-09-13 14:50 UTC by Tarek1311

Fix the  .pre-commit-config.yaml file

2022-09-13 19:37 UTC, Saxamos requested changes

2022-09-13 19:37 UTC, Saxamos commented on setup.py
> +                      "dash-auth==1.3.2"
connect this with the requirements.txt so we don't have duplicate :)

2022-09-13 19:37 UTC, Saxamos commented on setup.py
> +    packages=find_packages(include=['app', 'app.*']),
Can you explain me what does this do? Also why should we put app and app.* here?

2022-09-13 19:37 UTC, Saxamos commented on setup.py
> +    entry_points={"console_scripts": ["run = app.app:run"]},
Add this in the Readme ("you can use run to..., install the app with pip install -e .")

2022-09-14 08:14 UTC, Tarek1311 commented on setup.py
> +                      "dash-auth==1.3.2"
They were already connected with requirements.txt  :)

2022-09-15 14:36 UTC, Tarek1311 commented on setup.py
> +    packages=find_packages(include=['app', 'app.*']),
I did **“packages=find_packages(include=['app', 'app.*'])”**  
Because packages don't do any package lookup in the subtree. Adding a package to packages will only include the package itself and any direct submodules, but none of the subpackages.  
Packages imported into my app and listed in **PyPI** using **setuptools.findpackages**.

2022-09-16 11:53 UTC, Tarek1311 commented on setup.py
> +                      "dash-auth==1.3.2"
It's okay, the packages are connected with the requirements.txt without having diplucation

2022-09-16 11:54 UTC, Tarek1311 commented
Editing files app.py, setup.py and connect the packages with the requirements.txt without having duplicate

2022-09-16 12:42 UTC, Saxamos requested changes

2022-09-16 12:42 UTC, Saxamos commented on requirements.txt
> +setuptools==65.3.0
I don't think this is needed.

2022-09-16 12:42 UTC, Saxamos commented on app/app.py
> +    app.run_server(debug=True, port=8888)
Ok, add also the:
```
if __name__ == '__main__':
    run()
```
as I showed you :)

2022-09-16 12:42 UTC, Saxamos commented on C4Medical_Maids.egg-info/PKG-INFO
> +Metadata-Version: 2.1
Put this folder in the .gitignore, it should not be versionned!

2022-09-16 12:42 UTC, Saxamos commented on C4Medical_Maids.egg-info/PKG-INFO
> +Metadata-Version: 2.1
Everything with egg.info doesn't have anything to do here.

2022-09-16 12:42 UTC, Saxamos commented on setup.py
> +    packages=find_packages(include=["app", "app.*"]),
Is this still needed?

2022-09-16 12:42 UTC, Saxamos commented on setup.py
> +    install_requires=required,
Just do llike for the readme please:
```
install_requires=open("requirements.txt").read().splitlines()
```

2022-09-16 12:43 UTC, Saxamos commented on setup.py
> +    packages=find_packages(include=['app', 'app.*']),
I didn't understand. Please explain or remove :)

2022-09-16 12:43 UTC, Saxamos commented on setup.py
> +    entry_points={"console_scripts": ["run = app.app:run"]},
This hasn't been done Tarek.... You have to read every comments please.

2022-09-16 14:56 UTC, Tarek1311 commented on requirements.txt
> +setuptools==65.3.0
I removed it.

2022-09-16 14:58 UTC, Tarek1311 commented on app/app.py
> +    app.run_server(debug=True, port=8888)
It's ok, I added it.

2022-09-16 15:01 UTC, Tarek1311 commented on C4Medical_Maids.egg-info/PKG-INFO
> +Metadata-Version: 2.1
I added the C4Medical_Maids.egg-info folder in the .gitignore.

2022-09-16 15:30 UTC, Tarek1311 commented on setup.py
> +    packages=find_packages(include=["app", "app.*"]),
For now i have removed the part  ` **packages=find_packages(include=["app", "app.*"])**,` until I understand what its use is.

2022-09-16 15:34 UTC, Tarek1311 commented on setup.py
> +    packages=find_packages(include=['app', 'app.*']),
For now i have removed the part `packages=find_packages(include=["app", "app.*"])`, until I understand what its use is.

2022-09-16 15:43 UTC, Tarek1311 commented on setup.py
> +    entry_points={"console_scripts": ["run = app.app:run"]},
Sorry, it's noted. I did it!

2022-09-16 16:10 UTC, Tarek1311 commented on setup.py
> +    install_requires=required,
I added it to the readme file.

2022-09-16 16:27 UTC, Tarek1311 commented
Put C4Medical_Maids.egg-info in .gitignore and update readme, app.py, requirements.txt and setup.py

2022-09-21 13:33 UTC, Saxamos requested changes

2022-09-21 14:14 UTC, Saxamos approved these changes

2022-09-21 14:15 UTC, merged