update readme
Tarek1311/C4Medical_Maids pull request #8
Opened 2022-09-09 14:19 UTC by Tarek1311

2022-09-09 18:02 UTC, Tarek1311 commented
Confirmation for **README.md** page

2022-09-12 07:47 UTC, Saxamos requested changes

2022-09-12 07:47 UTC, Saxamos commented on README.md
> +**L'aplication a pour objectif d'apporter des solition concrète pour la vente et location de matériel/mobilier médical pour :**
solutions concrètes*

2022-09-12 07:47 UTC, Saxamos commented on README.md
> +       2. les professionnels de santé exerçant en libéral (hmédecins, infirmières, kinésithérapeutes, …) et les collectivités (hôpitaux, maisons de retraite, EHPAD, …)
médecins

2022-09-12 07:47 UTC, Saxamos commented on README.md
> +       2. les professionnels de santé exerçant en libéral (hmédecins, infirmières, kinésithérapeutes, …) et les collectivités (hôpitaux, maisons de retraite, EHPAD, …)
Pas de majuscule pour ce bullet point ?

2022-09-12 07:47 UTC, Saxamos commented on README.md
> +       3. Prestataire de santé à domicile (location d'un lit médicalisé, location de fauteuil roulant, mise en place d'une nutrition entérale à domicile…)
Le point 4 n'est pas correctement pris en compte on dirait. Aussi, il n'y a pas de majuscule.

2022-09-12 07:47 UTC, Saxamos commented on README.md
> +Afin de pouvoir exécuter l'application sur votre poste, vous devez d'aborder installer les dépendances suivantes :
d'abord*

2022-09-12 07:47 UTC, Saxamos commented on README.md
> +Afin de pouvoir exécuter l'application sur votre poste, vous devez d'aborder installer les dépendances suivantes :
précise la version de python et les commandes à executer (pip install -r requiremetns.txt) par exemple

2022-09-12 07:47 UTC, Saxamos commented on README.md
> +##  Cloner le repository git distant dans le répertoire local
Ca tu peux enlever :)

2022-09-12 07:47 UTC, Saxamos commented on README.md
> +Afin de pouvoir exécuter l'application sur votre poste, vous devez d'aborder installer les dépendances suivantes :
Ah mais tu l'as fait après. Donc tu peux enlever cette partie :)

2022-09-12 13:44 UTC, Tarek1311 commented
The readme file has been corrected

2022-09-12 14:42 UTC, Saxamos commented on README.md
> +## Prérequis
Pas utile, l'info est déjà après.

2022-09-12 15:07 UTC, Tarek1311 commented
The correction of mistakes  in README.md

2022-09-12 15:11 UTC, Tarek1311 commented on README.md
> +**L'aplication a pour objectif d'apporter des solition concrète pour la vente et location de matériel/mobilier médical pour :**
j'ai corrigé cette faute de frappe "des solutions concrètes"!!

2022-09-12 15:13 UTC, Tarek1311 commented on README.md
> +       2. les professionnels de santé exerçant en libéral (hmédecins, infirmières, kinésithérapeutes, …) et les collectivités (hôpitaux, maisons de retraite, EHPAD, …)
J'ai enlevé le h avant "médecins".

2022-09-12 15:14 UTC, Tarek1311 commented on README.md
> +       2. les professionnels de santé exerçant en libéral (hmédecins, infirmières, kinésithérapeutes, …) et les collectivités (hôpitaux, maisons de retraite, EHPAD, …)
J'ai mis le majuscule pour le bullet point.

2022-09-12 15:17 UTC, Tarek1311 commented on README.md
> +       3. Prestataire de santé à domicile (location d'un lit médicalisé, location de fauteuil roulant, mise en place d'une nutrition entérale à domicile…)
Maintenant le point 4 est correctement prise en compte.

2022-09-12 15:30 UTC, Tarek1311 commented on README.md
> +Afin de pouvoir exécuter l'application sur votre poste, vous devez d'aborder installer les dépendances suivantes :
- J'ai corrigé faute d'orthographe d'abord*
-  La version de python et la commandes à exécuter sont mentionnées

2022-09-12 15:31 UTC, Tarek1311 commented on README.md
> +##  Cloner le repository git distant dans le répertoire local
C'est fait 👍

2022-09-12 15:36 UTC, Tarek1311 commented on README.md
> +**L'aplication a pour objectif d'apporter des solition concrètes pour la vente et location de matériel/mobilier médical pour :**
La faute est corrigée :)

2022-09-12 15:48 UTC, Tarek1311 commented
Normalement tout est ok. Je vais être rigoureux.

2022-09-12 17:00 UTC, Saxamos approved these changes

2022-09-12 17:17 UTC, Tarek1311 commented
Merge feature/readme branch with master after Samuel's confirmation.

2022-09-12 17:22 UTC, Tarek1311 commented
Merge feature/readme  with master branch after Samuel's confirmation

2022-09-13 07:54 UTC, merged